# Site wide configuration

title: "Erin M. Roberts, Ph.D. Candidate"
description: "Documenting my research interests, goals, and accomplishments"
logo: images/oyster_photo.png  # 120x120 px default image used for Twitter summary card
teaser: images/oyster.png # 400x250 px default teaser image used in image archive grid
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

# Site owner
owner: 
  name:
  email: 
  twitter:
  google: 
    ad-client:
    ad-slot:
  bio:
  avatar: EMR_photo.jpeg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
